# Generated by Django 5.1 on 2024-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0002_latestupdate_reading_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurednews',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Featured News', 'verbose_name_plural': 'Featured News'},
        ),
        migrations.AlterModelOptions(
            name='latestupdate',
            options={},
        ),
        migrations.AddField(
            model_name='externalmediacontent',
            name='source_icon',
            field=models.FileField(blank=True, null=True, upload_to='source_icons/'),
        ),
        migrations.AddField(
            model_name='latestupdate',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Enter bullet points separated by a semicolon (;).'),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='reading_duration',
            field=models.CharField(blank=True, default='5 minutes read', max_length=20),
        ),
    ]
