# Generated by Django 5.1 on 2024-10-04 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0003_alter_featurednews_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=50)),
                ('code_to_embed', models.TextField(blank=True, help_text='Optional description or caption for the post', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='externalmediacontent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='featurednews',
            options={'ordering': ['-created'], 'verbose_name': 'Featured News', 'verbose_name_plural': 'Featured News'},
        ),
        migrations.AlterModelOptions(
            name='latestupdate',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='openposition',
            options={'ordering': ['-posted_date']},
        ),
        migrations.AlterModelOptions(
            name='pressrelease',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='featurednews',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='latestupdate',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='pressrelease',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='latestupdate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pressrelease',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pressrelease',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='externalmediacontent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='latestupdate',
            name='summary',
            field=models.TextField(blank=True, help_text='Optional summary of the article', verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Optional bullet points for the article. Enter bullet points separated by a semicolon (;)'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
