# Generated by Django 5.1 on 2024-10-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0004_socialmediapost_delete_gallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openposition',
            options={'ordering': ['-posted_on']},
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='requirements',
        ),
        migrations.AddField(
            model_name='openposition',
            name='biref_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='openposition',
            name='details',
            field=models.TextField(help_text='Job details', null=True),
        ),
        migrations.AddField(
            model_name='openposition',
            name='job_type',
            field=models.CharField(default='', help_text='Full-time, Part-time, etc', max_length=100),
        ),
        migrations.AddField(
            model_name='openposition',
            name='location',
            field=models.CharField(help_text='Remote, On-site, etc', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openposition',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('x', 'X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=50),
        ),
    ]
