# Generated by Django 5.1 on 2024-10-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0005_alter_openposition_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openposition',
            old_name='biref_description',
            new_name='brief_description',
        ),
    ]
