# Generated by Django 5.1 on 2024-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0008_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_large', models.CharField(help_text='Header text for large screens', max_length=200)),
                ('heading_small', models.CharField(help_text='Header text for small screens', max_length=200)),
                ('background_image', models.ImageField(help_text='Hero background image', upload_to='hero_images/')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
