# Generated by Django 5.1 on 2024-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0010_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='heading_large',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='heading_small',
        ),
        migrations.AddField(
            model_name='herosection',
            name='header_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='header_video',
            field=models.FileField(blank=True, help_text='Optional header video', null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional header background image', null=True, upload_to='hero_images/'),
        ),
    ]
