# Generated by Django 5.1 on 2024-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0011_remove_herosection_heading_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='header_video',
        ),
        migrations.AddField(
            model_name='herosection',
            name='banner_video',
            field=models.FileField(blank=True, help_text='Optional banner video', null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional banner image', null=True, upload_to='hero_images/'),
        ),
    ]
