# Generated by Django 5.1 on 2024-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muna_kalati', '0015_userprofile_linkedin_url_alter_latestupdate_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.FloatField(choices=[(1.0, '1.0 Stars'), (1.5, '1.5 Stars'), (2.0, '2.0 Stars'), (2.5, '2.5 Stars'), (3.0, '3.0 Stars'), (3.5, '3.5 Stars'), (4.0, '4.0 Stars'), (4.5, '4.5 Stars'), (5.0, '5.0 Stars')])),
            ],
        ),
    ]
